AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4.1

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
  - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/FileName:
  Description: Use snake_case for source file names.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#snake-case-files
  Enabled: false
