sudo: false
cache: bundler
language: ruby
rvm: 2.4.1
install:
  - bundle install --retry=3
before_script:
  - bundle exec rackup private_pub.ru -s thin -E production &
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec rspec --color --format documentation --require spec_helper --require rails_helper
  - bundle exec rubocop
